- name: Install nmcli components on client
  yum:
    name: NetworkManager-glib
    state: present

- name: Add IPv4 DNS server address
  nmcli:
    conn_name: System eth1
    type: ethernet
    dns4: 
    - "{{ dns }}"
    state: present

- name: Remove auto-dns
  shell: "nmcli con mod 'System eth0' ipv4.ignore-auto-dns yes"
  notify: restart network

- name: enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: firewalld ldap
  firewalld:
    zone: public
    service: freeipa-ldap
    permanent: yes
    state: enabled
    immediate: yes

- name: firewalld ldaps
  firewalld:
    zone: public
    service: freeipa-ldaps
    permanent: yes
    state: enabled
    immediate: yes

- name: firewalld dns
  firewalld:
    zone: public
    service: dns
    permanent: yes
    state: enabled
    immediate: yes

- name: Install freeIPA on client
  yum:
    name: freeipa-client
    state: present

- name: Setup client
  shell: "ipa-client-install -U --mkhomedir --force-ntpd --domain={{ domain }} --server={{ server }} --realm={{ realm }} --hostname={{ hostname }} -principal={{ principal }} --password={{ password }}"


